// We have 4 available drum machines: 606, 707, 808, 909:
707 i: \bd dur: 1;
707 i: \sn dur: 2 off: 1;
707 i: \oh dur: 0.25 beat: 1 amp: 0.4 degree: \rand length: 3 rotate: 1
707 i: \rd dur: 0.25 beat: 1 amp: 0.3
707 i: \ss dur: 1 off: 0.5 beat: 1 weight: 0.5

// 909
(
909 i: \bd dur: 1;
909 i: \sn dur: 2 off: 1;
909 i: \oh dur: 0.25 beat: 1 amp: 0.4 degree: \rand length: 3 rotate: 1;
909 i: \rd dur: 0.25 beat: 1 amp: 0.3;
909 i: \cr dur: 16 off: 4;
)